context:
  version: "0.43.3"

package:
  name: cpp-httplib
  version: ${{ version }}

source:
  url: https://github.com/yhirose/cpp-httplib/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8ccb5f498a9dc44769a49466986171b5cfaf89f3a54fd2eacfdc3fda5dfc7a6a

build:
  number: 0
  script:
    - if: unix
      then:
        - cmake -B build -G Ninja ${CMAKE_ARGS} -DHTTPLIB_COMPILE=OFF .
        - cmake --install build
      else:
        - cmake -B build -G Ninja %CMAKE_ARGS% -DHTTPLIB_COMPILE=OFF .
        - cmake --install build

requirements:
  build:
    - cmake
    - ninja
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - openssl

tests:
  - package_contents:
      include:
        - httplib.h

about:
  homepage: https://github.com/yhirose/cpp-httplib
  license: MIT
  license_file: LICENSE
  summary: A C++ header-only HTTP/HTTPS library
  description: |
    A C++11 single-file header-only cross platform HTTP/HTTPS library.
    It's extremely easy to setup. Just include the httplib.h file in your code!
  repository: https://github.com/yhirose/cpp-httplib

extra:
  recipe-maintainers:
    - amitsingh21
    - wolfv
