context:
  version: "0.43.4"

package:
  name: cpp-httplib
  version: ${{ version }}

source:
  url: https://github.com/yhirose/cpp-httplib/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ea125c932f6b9d0321ce1991434fc5a92fbce2ea1ee98fc1745a84872bb93d6c

build:
  number: 0
  script:
    - if: unix
      then:
        - cmake -B build -G Ninja ${CMAKE_ARGS} -DHTTPLIB_COMPILE=OFF .
        - cmake --install build
      else:
        - cmake -B build -G Ninja %CMAKE_ARGS% -DHTTPLIB_COMPILE=OFF .
        - cmake --install build

requirements:
  build:
    - cmake
    - ninja
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - openssl

tests:
  - package_contents:
      include:
        - httplib.h

about:
  homepage: https://github.com/yhirose/cpp-httplib
  license: MIT
  license_file: LICENSE
  summary: A C++ header-only HTTP/HTTPS library
  description: |
    A C++11 single-file header-only cross platform HTTP/HTTPS library.
    It's extremely easy to setup. Just include the httplib.h file in your code!
  repository: https://github.com/yhirose/cpp-httplib

extra:
  recipe-maintainers:
    - amitsingh21
    - wolfv
